// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ1f06bxrZuiumIM3Iz8bWUV8Zy44bDSM',
    appId: '1:504007880137:web:aebb75f58a158013ad8c18',
    messagingSenderId: '504007880137',
    projectId: 'u6a1-flutter',
    authDomain: 'u6a1-flutter.firebaseapp.com',
    storageBucket: 'u6a1-flutter.firebasestorage.app',
    measurementId: 'G-L9ET40DWPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWAZhKq3vi4WowkcT0idf7WX5D2VDGf5A',
    appId: '1:504007880137:android:ede7c61c7bd151ddad8c18',
    messagingSenderId: '504007880137',
    projectId: 'u6a1-flutter',
    storageBucket: 'u6a1-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ503ZwsRd2oZC-4NNEttcxUQ5RjDxZQg',
    appId: '1:504007880137:ios:3730bf6e1cbcd3f1ad8c18',
    messagingSenderId: '504007880137',
    projectId: 'u6a1-flutter',
    storageBucket: 'u6a1-flutter.firebasestorage.app',
    iosBundleId: 'com.example.u3ga1Marcosrubio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ503ZwsRd2oZC-4NNEttcxUQ5RjDxZQg',
    appId: '1:504007880137:ios:3730bf6e1cbcd3f1ad8c18',
    messagingSenderId: '504007880137',
    projectId: 'u6a1-flutter',
    storageBucket: 'u6a1-flutter.firebasestorage.app',
    iosBundleId: 'com.example.u3ga1Marcosrubio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ1f06bxrZuiumIM3Iz8bWUV8Zy44bDSM',
    appId: '1:504007880137:web:c8c03bee62ade5d4ad8c18',
    messagingSenderId: '504007880137',
    projectId: 'u6a1-flutter',
    authDomain: 'u6a1-flutter.firebaseapp.com',
    storageBucket: 'u6a1-flutter.firebasestorage.app',
    measurementId: 'G-11NXMXC7M0',
  );
}
